stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - libero-soc-v2023.2
  variables:
    BUILD_OPTIONS_DIRECTORY: "custom-fpga-design"
    BRANCH_UNDER_TEST: "develop"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop")
      variables:
        BUILD_OPTIONS_DIRECTORY: "build-options"
        REPO_UNDER_TEST: $CI_MERGE_REQUEST_SOURCE_PROJECT_URL
        BRANCH_UNDER_TEST: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - if: $CI_PIPELINE_SOURCE == "push"
      variables:
        BUILD_OPTIONS_DIRECTORY: "custom-fpga-design"
        REPO_UNDER_TEST: $CI_PROJECT_URL
        BRANCH_UNDER_TEST: $CI_COMMIT_BRANCH
        
  script:
    - echo "Cloning the tester and gateware..."
    - export
    - source ~/Microchip/Microchip-FPGA-Tools-Setup/setup-microchip-tools.sh
    - git clone https://git.beagleboard.org/beaglev-fire/gateware-builds-tester.git
    - cd gateware-builds-tester
    - git clone $REPO_UNDER_TEST -b $BRANCH_UNDER_TEST
    - echo "Building the gateware..."
    - python3 bitstream-builds-tester.py $REPO_UNDER_TEST $BUILD_OPTIONS_DIRECTORY
    - echo "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
    - echo "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    - echo "Compile complete."
  artifacts:
    when: on_success
    paths:
      - gateware-builds-tester/artifacts/
    reports:
      junit: gateware-builds-tester/artifacts/tests_report.xml

pages:
  image: robertcnelson/beagle-devscripts-ubuntu-23.04-riscv64:latest
  # https://git.beagleboard.org/beagleboard/ci-docker-images
  stage: deploy
  tags:
    - docker-riscv64-ci
  variables:
    BUILD_OPTIONS_DIRECTORY: "custom-fpga-design"
    BRANCH_UNDER_TEST: "develop"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop")
      variables:
        BUILD_OPTIONS_DIRECTORY: "build-options"
        REPO_UNDER_TEST: $CI_MERGE_REQUEST_SOURCE_PROJECT_URL
        BRANCH_UNDER_TEST: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
        DEBIAN_CHANGELOG_PKG: "bbb.io-gateware"
        DEBIAN_SRC: "debian"
    - if: $CI_PIPELINE_SOURCE == "push"
      variables:
        BUILD_OPTIONS_DIRECTORY: "custom-fpga-design"
        REPO_UNDER_TEST: $CI_PROJECT_URL
        BRANCH_UNDER_TEST: $CI_COMMIT_BRANCH
        DEBIAN_CHANGELOG_PKG: "bbb.io-gateware-my-custom-fpga-design"
        DEBIAN_SRC: "debian-custom"
  script:
    - rm -rf ./src/ || true
    - mkdir -p ./src/debian/ || true
    - rsync -av ./$DEBIAN_SRC/* ./src/debian/
    - mkdir -p ./src/gateware-builds-tester || true
    - rsync -av ./gateware-builds-tester/* ./src/gateware-builds-tester/
    - echo "$DEBIAN_CHANGELOG_PKG (1.$(LANG=C date +%Y%m%d).0-0~lunar) lunar; urgency=low" > ./src/debian/changelog
    - echo "" >> ./src/debian/changelog
    - echo "  * ci build of $CI_PROJECT_URL" >> ./src/debian/changelog
    - echo "" >> ./src/debian/changelog
    - echo " -- $GITLAB_USER_NAME <$GITLAB_USER_EMAIL>  $(LANG=C date -R)" >> ./src/debian/changelog
    - echo "" >> ./src/debian/changelog
    - cat ./src/debian/changelog
    - cd ./src/ ; debuild -b -us -uc ; cd ../
    - mkdir -p ./public/dists/stable/main/binary-riscv64/
    - mkdir -p ./public/pool
    - cp -v *.deb ./public/pool/ || true
    - cp -v *.build ./public/ || true
    - cp -v *.buildinfo ./public/ || true
    - cd ./public ; dpkg-scanpackages ./pool/ | gzip > ./dists/stable/main/binary-riscv64/Packages.gz || true ; cd ../
    - apindex public
  artifacts:
    when: on_success
    paths:
      - public
